# Generated by Django 4.0.6 on 2022-09-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_image_url_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_url',
            field=models.ImageField(default='user_profile/default_profile.jpg', upload_to='user_profile'),
        ),
    ]
