# Generated by Django 4.0.6 on 2022-09-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='user_profile/default_profile.jpg', null=True, upload_to='user_profile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_image',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
