# Generated by Django 3.2.16 on 2023-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_image_url_customuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='media/profile_pictures/default_profile.jpg', null=True, upload_to='media/profile_pictures'),
        ),
    ]
