# Generated by Django 3.2.16 on 2023-09-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile.jpeg', null=True, upload_to='profile_pictures'),
        ),
    ]
