# Generated by Django 4.0.6 on 2022-09-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
