# Generated by Django 3.2.16 on 2022-10-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_log_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
